// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtJqeKlC5CPpXMz7Uk0LrzxbpOUgcSWm0',
    appId: '1:494020145923:web:8a7d328f1e74b51aaaaf36',
    messagingSenderId: '494020145923',
    projectId: 'fir-demo-8c0e6',
    authDomain: 'fir-demo-8c0e6.firebaseapp.com',
    storageBucket: 'fir-demo-8c0e6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCji4prkvEoreNPeLG7rPA1ws-qb2RjXKI',
    appId: '1:494020145923:android:779134d9ebf5707daaaf36',
    messagingSenderId: '494020145923',
    projectId: 'fir-demo-8c0e6',
    storageBucket: 'fir-demo-8c0e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKemuVEOi9APpFPrADY-WDvmBaMgzqLWo',
    appId: '1:494020145923:ios:b078274c64f25bb3aaaf36',
    messagingSenderId: '494020145923',
    projectId: 'fir-demo-8c0e6',
    storageBucket: 'fir-demo-8c0e6.appspot.com',
    iosClientId: '494020145923-55o4drrdst0k4np8r4kfnga6dpot58pm.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKemuVEOi9APpFPrADY-WDvmBaMgzqLWo',
    appId: '1:494020145923:ios:b078274c64f25bb3aaaf36',
    messagingSenderId: '494020145923',
    projectId: 'fir-demo-8c0e6',
    storageBucket: 'fir-demo-8c0e6.appspot.com',
    iosClientId: '494020145923-55o4drrdst0k4np8r4kfnga6dpot58pm.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseDemo',
  );
}
